# Generated by Django 5.2.6 on 2025-09-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, help_text='Altura en metros (ej: 1.75)', max_digits=5, null=True)),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kilogramos', max_digits=5, null=True)),
                ('alergias', models.TextField(blank=True)),
                ('medicamentos', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['usuario__last_name', 'usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='RegistroHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notas', models.TextField(blank=True)),
                ('circunferencia_cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('circunferencia_cadera', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Historial',
                'verbose_name_plural': 'Registros de Historial',
                'ordering': ['-fecha'],
            },
        ),
    ]
